In [37]:
import torch

In [38]:
x = torch.rand((2, 3))
x = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print(x.shape)
x

torch.Size([2, 3])


tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [39]:
# permutation
torch.einsum('ij -> ji', x)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [40]:
# summation over all
print(torch.einsum('ij ->', x), x.sum())

tensor(21.) tensor(21.)


In [41]:
# row sum
torch.einsum('ij -> i', x)

tensor([ 6., 15.])

In [42]:
# colsum
torch.einsum('ij -> j', x)

tensor([5., 7., 9.])

In [43]:
# matrix vector multiplication
v = torch.Tensor([0.5, 1, 2])
torch.einsum('ij, j -> ij', x, v)

tensor([[ 0.5000,  2.0000,  6.0000],
        [ 2.0000,  5.0000, 12.0000]])

In [44]:
# matrix vecotr multiplication
v = torch.Tensor([0.5, 2])
torch.einsum('ij, i -> ij', x, v)

tensor([[ 0.5000,  1.0000,  1.5000],
        [ 8.0000, 10.0000, 12.0000]])

In [27]:
# matrix matrix multiplication
m = torch.Tensor([[1,2,3,4], [5,6,7,8]])
torch.einsum('ij, ik -> jk', x, m)

tensor([[21., 26., 31., 36.],
        [27., 34., 41., 48.],
        [33., 42., 51., 60.]])

In [31]:
x.T@m

tensor([[21., 26., 31., 36.],
        [27., 34., 41., 48.],
        [33., 42., 51., 60.]])

In [77]:
# Hadamard Product (element-wise multiplication)
torch.einsum('ij,ij->ij', x, x)

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

In [78]:
# dot product
x.T@v

# (2, 3) (2)
torch.einsum('ij, i -> j', x, v)

tensor([ 8.5000, 11.0000, 13.5000])

In [80]:
# Outer Product
a = torch.rand((3))
b = torch.rand((5))
torch.einsum('i,j->ij',a,b)

tensor([[0.1588, 0.1285, 0.0539, 0.0897, 0.1565],
        [0.3196, 0.2585, 0.1084, 0.1805, 0.3149],
        [0.2209, 0.1787, 0.0749, 0.1248, 0.2177]])

In [82]:
# Batched Matrix Multiplication
a = torch.rand((3, 2, 5))
b = torch.rand((3, 5, 3))
# want (3, 2, 3)

torch.einsum('ijk, ikl -> ijl', a, b).shape

torch.Size([3, 2, 3])

In [125]:
# matrix diagonal
x = torch.diag(torch.rand(3))
print(x)
torch.einsum('ii->i', x)

tensor([[0.1421, 0.0000, 0.0000],
        [0.0000, 0.9151, 0.0000],
        [0.0000, 0.0000, 0.7863]])


tensor([0.1421, 0.9151, 0.7863])

In [126]:
# matrix trace
torch.einsum('ii->', x)

tensor(1.8435)

In [127]:
m = torch.Tensor([[1,2,3], [4,5,6]])
v = torch.Tensor([1,2,3]) 

In [128]:
torch.einsum('i,i -> i', v,v)

tensor([1., 4., 9.])

In [137]:
# repeating letter in input -> multiplication
# omitting letter in output -> sum
# any permuation possible

In [143]:
v = torch.Tensor([1,2,3])
a = torch.Tensor([1,2,3,4])
torch.einsum('i,j -> i', v, a)

tensor([10., 20., 30.])

In [139]:
torch.einsum('i,i -> i', v,v)

tensor([1., 4., 9.])